# Generated by Django 5.2.1 on 2025-05-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=45)),
                ('tipo', models.CharField(max_length=45)),
                ('material', models.CharField(max_length=45)),
                ('imagen', models.CharField(max_length=200)),
                ('precio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('imagen', models.CharField(max_length=200)),
                ('horario', models.CharField(max_length=45)),
                ('telefonos', models.CharField(max_length=50)),
            ],
        ),
    ]
