# Generated by Django 5.2.1 on 2025-05-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donontiveros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Productos',
        ),
    ]
