# Generated by Django 5.2.1 on 2025-05-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donontiveros', '0002_rename_producto_productos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
