# Generated by Django 5.2.1 on 2025-05-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donontiveros', '0003_rename_productos_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
    ]
