# Generated by Django 5.2.1 on 2025-05-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donontiveros', '0004_alter_sucursal_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('departamento', models.CharField(max_length=20)),
                ('proyectos', models.CharField(max_length=25)),
                ('antiguedad', models.CharField(max_length=6)),
            ],
        ),
    ]
