# Generated by Django 5.2.1 on 2025-05-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donontiveros', '0005_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=160)),
                ('logo', models.CharField(max_length=200)),
            ],
        ),
    ]
