# Generated by Django 5.2.1 on 2025-05-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donontiveros', '0007_empleado_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('mensaje', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
