# Generated by Django 5.2.1 on 2025-05-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=45)),
                ('imagen', models.CharField(max_length=55)),
                ('precio', models.CharField(max_length=50)),
            ],
        ),
    ]
